using SimpLedger.Repository.Configurations;

namespace SimpLedger.Repository.Interfaces.Account
{
    public interface ISetTokenSevice
    {
        /// <summary>
        ///  Generating a JWT cookie token
        /// </summary>
        /// <param name="id">User id for identification of claims</param>
        /// <param name="name">User name</param>
        /// <returns>Return a secure Jwt token string</returns>
        string GenerateJwtToken(int id, string name);

        /// <summary>
        ///  This will provide a secure hashed value base on user define value and random salt value
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="value">Generic type user define value like raw password etc</param>
        /// <param name="salt">Random base64 string generated by GenerateSalt() </param>
        /// <returns>Return a hashed string</returns>
        string Hashed<T>(T value, string salt);

        /// <summary>
        ///  This will generate value between 100000 - 999999
        /// </summary>
        /// <returns>Return a random number</returns>
        int GenerateCode();

        /// <summary>
        ///  This will generate random base64 string
        /// </summary>
        /// <returns>Return a base64 string</returns>
        string GenerateSalt();

        /// <summary>
        ///   This will generate hashed generic/local token used for verification. (This can't be issue as user cookie token)
        /// </summary>
        /// <param name="code">User define value to be hashed together with random salt string</param>
        /// <returns></returns>
        string GenerateGenericToken(int code);

        /// <summary>
        ///     This will set the cookie in httpcontext
        /// </summary>
        /// <param name="tokenName">Name of the token issue to the user</param>
        /// <param name="actualToken">The actual token obtain in GenerateJwtToken()</param>
        /// <param name="httpContextSettings">Httpcontext settings bind in Appsettings</param>
        /// <param name="context">The actual context of user request</param>
        /// <returns></returns>
        HttpContext SetCookie(string tokenName, string actualToken, HttpContextSettings httpContextSettings, HttpContext context);
    }
}
